# Generated by Django 2.0.3 on 2018-11-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181115_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='encode',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
