# Generated by Django 2.0.3 on 2018-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20181116_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mac_addres',
            field=models.TextField(default='00:00:00:00:00:00', max_length=17),
        ),
    ]
