# Generated by Django 2.0.3 on 2018-11-25 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_profile_mac_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mac_addres',
            new_name='mac_address',
        ),
    ]
